spring.application.name=hql-jpql
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=asmetop7!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.cognizant.hqljpql=DEBUG