server.port=8888
spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///D:/DN5-JavaFSE/Week4/Microservices/0_Sample_Microservices_exercises/config-repo